[package]
name = "momentary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0"
rusqlite = "0.31.0"
tera = "1.19.1"

[dependencies.rocket_dyn_templates]
features = ["tera"]
